actions:
  - name: "ğŸŒ  Translate"
    command: "dict.sh '{}'"

  - name: "ğŸ”¤  Deepl"
    command: "deepl text --to ko '{}'"

  - name: "ğŸ•°ï¸  Epoch to Date"
    command: "date -d @{} '+%Y-%m-%d %H:%M:%S'"

  - name: "ğŸ”Š  Speak"
    command: "speak '{}'; echo {}"

  - name: "ğŸ’¬  Explain"
    command: "echo '{}' | aichat 'í•œê¸€ë¡œ ì˜ë¯¸ë¥¼ ì„¤ëª…í•´. markdownì´ ì•„ë‹Œ plaintext í˜•ì‹ìœ¼ë¡œ ì‘ë‹µí•´'"

  - name: "â“  Ask"
    command: "aichat '{}'"

  - name: " âœï¸ Rewrite"
    command: "echo '{}' | aichat 'Rewrite this sentences to make it sound more professional and formal while keeping the original message intact.'"

  - name: "ğŸ•’  Print Now"
    command: "date '+%Y-%m-%d %H:%M:%S'; date +%s"
